# Generated by Django 5.2.8 on 2025-11-27 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_login", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facultyerplogin",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Faculty ERP Login",
                "verbose_name_plural": "Faculty ERP Logins",
            },
        ),
        migrations.AlterModelOptions(
            name="studenterplogin",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Student ERP Login",
                "verbose_name_plural": "Student ERP Logins",
            },
        ),
        migrations.AddField(
            model_name="facultyerplogin",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="facultyerplogin",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Inactive faculty cannot login"
            ),
        ),
        migrations.AddField(
            model_name="facultyerplogin",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="studenterplogin",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="studenterplogin",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Inactive students cannot login"
            ),
        ),
        migrations.AddField(
            model_name="studenterplogin",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="facultyerplogin",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="facultyerplogin",
            name="password_hash",
            field=models.CharField(help_text="Hashed password", max_length=256),
        ),
        migrations.AlterField(
            model_name="facultyerplogin",
            name="username",
            field=models.CharField(
                help_text="Faculty official username", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="studenterplogin",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="studenterplogin",
            name="password_hash",
            field=models.CharField(help_text="Hashed password", max_length=256),
        ),
        migrations.AlterField(
            model_name="studenterplogin",
            name="username",
            field=models.CharField(
                help_text="University roll number", max_length=50, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="facultyerplogin",
            index=models.Index(
                fields=["username"], name="erp_login_f_usernam_ab5d7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facultyerplogin",
            index=models.Index(fields=["email"], name="erp_login_f_email_553fca_idx"),
        ),
        migrations.AddIndex(
            model_name="studenterplogin",
            index=models.Index(
                fields=["username"], name="erp_login_s_usernam_4312b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studenterplogin",
            index=models.Index(fields=["email"], name="erp_login_s_email_85b329_idx"),
        ),
    ]
